### ISSUE TITLE
Mobile swipe not working

### ISSUE THREAD

**Issue by bethblinebury** [BeSite/jQuery.TosRUs#59]
Hey there,
This plugin is great! I can't seem to get the touch gestures to work on mobile though. I have the min.all.js file loaded along with hammer.js. 

I'm not sure what the issue is. Thanks in advance for your help! 

Page with issue: http://bethblineburydesign.com/about-philadelphia-beth-blinebury-design/beth-blinebury/

**Comment by bethblinebury** [comment]
I've continued to test this and still no luck on mobile. I've tried older versions of both the tosus.js files with an older version of hammer.js. I even tried setting my jQuery version back and no luck.

**Comment by bethblinebury** [comment]
Any ideas?

**Comment by FrDH** [comment]
Hi, sorry for the late reply.
I'm not sure why, but after the lightbox opens, the page is redirected to the image itself. Are you running any other scripts that might cause this behavior?

**Comment by bethblinebury** [comment]
Hey there! I had some outbound link tracking that was disabling the lightbox on all views. That has been removed. However, if you check on mobile, the lightbox continues to not swipe. I'm just not sure what's up with it - any help would be appreciated. Thanks!

**Comment by FrDH** [comment]
Are you getting any errors in the console?
What is alerted if you put this js somewhere:
````javascript
$(function() {
  alert( $.tosrus.support.touch );
});
````

**Comment by wlekin** [comment]
I have the same issue as you,  
hammerJS working well and "$.tosrus.support.touch" return true in my mobile but, however, swipe function just not working~
please look in to my page and give me some advice... Thanks!
http://106.187.95.184/0/tosrus/

**Comment by bethblinebury** [comment]
I am not getting any errors. I'm not sure why it's not working but swipe on mobile is still not functional.

**Comment by FrDH** [comment]
My guess is, HammerJS isn't yet loaded when the drag add-on initializes:

````javascript
if ( typeof Hammer != 'function' ) {
    return;
}
````

In other words, HammerJS and Tosrus need to load synchronously.

**Comment by wlekin** [comment]
thanks, it works.

**Comment by bethblinebury** [comment]
Thanks, that did the trick!
