### ISSUE TITLE
Loading icon

### ISSUE THREAD

**Issue by mrlevinson** [BeSite/jQuery.TosRUs#63]
Is there a way to add a loading icon? Usually the pictures load really fast, but every once in a while it takes a minute. Is there a way to add a loading icon/animated gif?

Awesome script, by the way.
-Noah

**Comment by FrDH** [comment]
The classname "tos-loading" is added by default to each slide, it is removed after the slide finished loading. 

Note that only images have an actuall "onLoad" callback. All other media remove the classname directly when the slide starts loading.
