### ISSUE TITLE
How to fire plugin once generally for every instance with rel=”variable” lightbox way?

### ISSUE THREAD

**Issue by sampraa** [BeSite/jQuery.TosRUs#67]
Is there a way how to once fire plugin generally for all instances with “rel=” like lightbox does?
My WYSIWYG  CK editor enables users to insert images and assign it to some groups. Output is something like: 
&lt;a href=”” rel=”group[a]”&gt;  &lt; /a&gt;   &lt;a href=”” rel=”group[a]”&gt; &lt;/a&gt;  ...
&lt;a href=”” rel=”group[b]”&gt;  &lt;/a&gt;   &lt;a href=”” rel=”group[b]”&gt;  &lt;/a&gt;  ....
So when you click on thumbnail with rel=”group[a]” you will browse all images with rel=”group[a]” etc. 

Is it possible to run tosrus() that way? I.e. to run one function which will fire for every instance with some pattern, for example rel=”group[?]”, special tosrus()?

**Comment by FrDH** [comment]
Not by default, but I guess something like this should work:
````javascript
var rels = {};
$('a[rel]').each(function() {
    rels[ $(this).attr( 'rel' ) ] = 1;
});
console.log(rels)
$.each(rels, function( r ) {
    $('a[rel="' + r + '"]').tosrus();
});
````
