### ISSUE TITLE
[SOLVED] Miss option separate galleries

### ISSUE THREAD

**Issue by Arnopello** [BeSite/jQuery.TosRUs#72]
Hi

I find your plugin amazing, even putting myself in the trouble of configuring it by hand for wordpress (with no Xp in JS programming) instead of using a WP plugin. 
I find an option missing: prevent the lightbox from going to the next image/gallery after the last image is reached. Also, prevent the pagination from showing pictures of all galeries. 

Regards

BTW I also meet this problem : https://github.com/BeSite/jQuery.TosRUs/issues/71

**Comment by FrDH** [comment]
The plugin groups images into a gallery by the selector:
````javascript
// create one gallery of all anchors in ".gallery"
$(".gallery a").tosrus(); 

// create a gallery for each ".gallery"
$(".gallery").each(function() {
  $(this).find( "a" ).tosrus();
});
````
Hope this helps.

**Comment by Arnopello** [comment]
Works like a charm, thanks!
Might be useful for others.
